-- =============================================================================
-- Cloud-Based Video Fingerprint Collection System
-- Supabase PostgreSQL Schema
-- =============================================================================
-- Run this script in the Supabase SQL Editor to set up the database.
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. CREATE TABLE: fingerprints
-- Each row represents a single video-frame fingerprint captured by the dashcam
-- driver unit and transmitted to the cloud in real-time.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fingerprints (
  -- Primary key: UUID generated by the database to guarantee uniqueness and
  -- prevent collisions even if multiple vehicles stream simultaneously.
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The SHA-256 hash of the video frame (hex-encoded, always 64 characters).
  -- A strict CHECK constraint enforces the exact format here at the DB layer,
  -- providing a second line of defence beyond the application-level validation.
  hash TEXT NOT NULL
    CHECK (
      length(hash) = 64
      AND hash ~ '^[a-f0-9]+$'
    ),

  -- Simulated video-frame timestamp (Unix epoch milliseconds).
  -- Stored as BIGINT so that sub-second precision is preserved without
  -- floating-point rounding errors — critical for accident-claim sequencing.
  frame_timestamp BIGINT NOT NULL,

  -- Server-side insertion time, set automatically to "now()" so the insurance
  -- company can prove when data arrived at the cloud, independent of client
  -- clocks (important for tamper-evidence).
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index on created_at to allow fast chronological range queries by the
-- insurance dashboard (e.g., "all frames from a specific accident window").
CREATE INDEX IF NOT EXISTS idx_fingerprints_created_at
  ON public.fingerprints (created_at DESC);

-- Index on frame_timestamp for ordering frames in video-playback order.
CREATE INDEX IF NOT EXISTS idx_fingerprints_frame_timestamp
  ON public.fingerprints (frame_timestamp ASC);


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. ENABLE ROW LEVEL SECURITY (RLS)
-- RLS is enabled on every table in Supabase by default for production safety.
-- For this PoC we define simple, permissive policies. In production these would
-- be scoped to authenticated roles (e.g., "driver" vs "insurance_admin").
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.fingerprints ENABLE ROW LEVEL SECURITY;

-- Policy: Allow any client (anon key) to INSERT new fingerprints.
-- In production: restrict to authenticated "driver" role only.
CREATE POLICY "allow_anon_insert"
  ON public.fingerprints
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Policy: Allow any client (anon key) to SELECT / READ fingerprints.
-- In production: restrict to authenticated "insurance_admin" role only.
CREATE POLICY "allow_anon_select"
  ON public.fingerprints
  FOR SELECT
  TO anon
  USING (true);


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. ENABLE SUPABASE REALTIME
-- Adding the table to the supabase_realtime publication enables the Realtime
-- engine to broadcast change events (INSERT, UPDATE, DELETE) via WebSockets.
-- The insurance admin dashboard subscribes to these events to display incoming
-- fingerprints without polling.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE public.fingerprints;


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. VERIFICATION QUERY (optional — run to confirm setup)
-- ─────────────────────────────────────────────────────────────────────────────
-- SELECT tablename, rowsecurity
--   FROM pg_tables
--  WHERE schemaname = 'public' AND tablename = 'fingerprints';
